version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      timezone: "Asia/Seoul"
    target-branch: "develop"
    assignees:
      - "keelim"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "github actions"
      - "dependencies"
