name: develop CI

on:
  push:
    tags:
      - DEV*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: bash ./gradlew assembleDevDebug
    - name: Set tag name env
      run: echo ::set-env name=DEVELOP_VERSION::${GITHUB_REF#refs/*/}
    - name: check tag name
      run: |
        echo $DEVELOP_VERSION
        echo ${{ env.DEVELOP_VERSION }}
    - name: change file name
      run: mv app/build/outputs/apk/dev/debug/app-dev-debug.apk app/build/outputs/apk/dev/debug/${{ env.DEVELOP_VERSION }}.apk
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.DEVELOP_VERSION }}
        path: app/build/outputs/apk/dev/debug/${{ env.DEVELOP_VERSION }}.apk
