on:
  workflow_dispatch:

jobs:
  app_cnubus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3.8.0
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Add Google Service Json
        run: echo '${{ secrets.CNUBUS_GOOGLE_SERVICES_JSON }}' > ./app-cnubus/google-services.json

      - name: ADD LOCAL PROPERTIES
        env:
          APOD_API_KEY: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo '${{ secrets.LOCAL_PROPERTIES }}' > ./local.properties

      - name: Build with Gradle
        run: ./gradlew app-cnubus:build
  app_comssa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3.8.0
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Add Google Service Json
        run: echo '${{ secrets.COMSSA_GOOGLE_SERVICES_JSON }}' > ./app-comssa/google-services.json

      - name: ADD LOCAL PROPERTIES
        env:
          APOD_API_KEY: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo '${{ secrets.LOCAL_PROPERTIES }}' > ./local.properties

      - name: Build with Gradle
        run: ./gradlew app-comssa:build
  app_mygrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3.8.0
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Add Google Service Json
        run: echo '${{ secrets.MYGRADE_GOOGLE_SERVICES_JSON }}' > ./app-my-grade/google-services.json

      - name: ADD LOCAL PROPERTIES
        env:
          APOD_API_KEY: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo '${{ secrets.LOCAL_PROPERTIES }}' > ./local.properties

      - name: Build with Gradle
        run: ./gradlew app-my-grade:build
  app_nanda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3.8.0
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Add Google Service Json
        run: echo '${{ secrets.NANDA_GOOGLE_SERVICES_JSON }}' > ./app-nanda/google-services.json

      - name: ADD LOCAL PROPERTIES
        env:
          APOD_API_KEY: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo '${{ secrets.LOCAL_PROPERTIES }}' > ./local.properties

      - name: Build with Gradle
        run: ./gradlew app-nanda:build
