on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: cache gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.4.2
        with:
          validate-wrappers: true
          gradle-version: current
          gradle-home-cache-cleanup: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set environment
        run: |
          echo '${{ secrets.GOOGLE_SERVICE_JSON }}' | base64 -d > ./app-cnubus/google-services.json
          echo '${{ secrets.GOOGLE_SERVICE_JSON }}' | base64 -d > ./app-comssa/google-services.json
          echo '${{ secrets.GOOGLE_SERVICE_JSON }}' | base64 -d > ./app-my-grade/google-services.json
          echo '${{ secrets.GOOGLE_SERVICE_JSON }}' | base64 -d > ./app-nanda/google-services.json
          echo '${{ secrets.GOOGLE_SERVICE_JSON }}' | base64 -d > ./app-arducon/google-services.json
          echo '${{ secrets.LOCAL_PROPERTIES }}' | base64 -d > ./local.properties
          echo '${{ secrets.FONTS }}' | base64 -d > ./core/compose-core/src/main/res/values/font_certs.xml

      - name: Build with Gradle
        run: |
          ./gradlew app-comssa:assembleRelease app-cnubus:assembleRelease app-my-grade:assembleRelease app-nanda:assembleRelease app-arducon:assembleRelease

      - name: Build Release AAB
        id: buildRelease
        run: |
          ./gradlew app-comssa:bundleRelease app-cnubus:bundleRelease app-my-grade:bundleRelease app-nanda:bundleRelease app-arducon:bundleRelease

      - name: Sign Comssa AAB
        id: sign_comssa
        uses: keelim/upload-google-play@0.0.2
        with:
          type: sign
          releaseDirectory: app-comssa/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.COMSSA_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Sign Cnubus AAB
        id: sign_cnubus
        uses: keelim/upload-google-play@0.0.2
        with:
          type: sign
          releaseDirectory: app-cnubus/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.CNUBUS_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Sign MyGrade AAB
        id: sign_mygrade
        uses: keelim/upload-google-play@0.0.2
        with:
          type: sign
          releaseDirectory: app-my-grade/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.MYGRADE_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Sign Nanda AAB
        id: sign_nanda
        uses: keelim/upload-google-play@0.0.2
        with:
          type: sign
          releaseDirectory: app-nanda/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.NANDA_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Sign Arducon AAB
        id: sign_arducon
        uses: keelim/upload-google-play@0.0.2
        with:
          type: sign
          releaseDirectory: app-arducon/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ARDUCON_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Create service_account.json
        id: createServiceAccount
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Deploy to Play Store Cnubus
        id: deploy_cnubus
        uses: keelim/upload-google-play@0.0.2
        with:
          type: upload
          serviceAccountJson: service_account.json
          packageName: com.keelim.cnubus
          releaseFiles: app-cnubus/build/outputs/bundle/release/app-cnubus-release.aab
          track: production
          status: completed
          changesNotSentForReview: false

      - name: Deploy to Play Store Comssa
        id: deploy_comssa
        uses: keelim/upload-google-play@0.0.2
        with:
          type: upload
          serviceAccountJson: service_account.json
          packageName: com.keelim.comssa
          releaseFiles: app-comssa/build/outputs/bundle/release/app-comssa-release.aab
          track: production
          status: completed
          changesNotSentForReview: false

      - name: Deploy to Play Store MyGrade
        id: deploy_mygrade
        uses: keelim/upload-google-play@0.0.2
        with:
          type: upload
          serviceAccountJson: service_account.json
          packageName: com.keelim.mygrade
          releaseFiles: app-my-grade/build/outputs/bundle/release/app-my-grade-release.aab
          track: production
          status: completed
          changesNotSentForReview: false

      - name: Deploy to Play Store Nanda
        id: deplo_nanda
        uses: keelim/upload-google-play@0.0.2
        with:
          type: upload
          serviceAccountJson: service_account.json
          packageName: com.keelim.nandadiagnosis
          releaseFiles: app-nanda/build/outputs/bundle/release/app-nanda-release.aab
          track: production
          status: completed
          changesNotSentForReview: false

      - name: Deploy to Play Store Arducon
        id: deplo_arducon
        uses: keelim/upload-google-play@0.0.2
        with:
          type: upload
          serviceAccountJson: service_account.json
          packageName: com.keelim.arducon
          releaseFiles: app-arducon/build/outputs/bundle/release/app-arducon-release.aab
          track: production
          status: completed
          changesNotSentForReview: true
