on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: set up JDK 17
        uses: actions/setup-java@v4.7.1
        with:
          distribution: "zulu" # See 'Supported distributions' for available options
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set environment
        run: |
          echo '${{ secrets.GOOGLE_SERVICE_JSON }}' | base64 -d> ./app-my-grade/google-services.json
          echo '${{ secrets.LOCAL_PROPERTIES }}' | base64 -d > ./local.properties
          echo '${{ secrets.FONTS }}' | base64 -d > ./core/compose-core/src/main/res/values/font_certs.xml

      - name: Build Release AAB
        id: buildRelease
        run: ./gradlew app-my-grade:bundleRelease

      - name: Sign AAB
        id: sign
        uses: keelim/upload-google-play@v0.0.5
        with:
          type: sign
          releaseDirectory: app-my-grade/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.MYGRADE_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Create service_account.json
        id: createServiceAccount
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Deploy to Play Store
        id: deploy
        uses: keelim/upload-google-play@v0.0.5
        with:
          type: upload
          serviceAccountJson: service_account.json
          packageName: com.keelim.mygrade
          releaseFiles: app-my-grade/build/outputs/bundle/release/app-my-grade-release.aab
          track: production
          status: completed
          changesNotSentForReview: true
