on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: cache gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: set up JDK 17
        uses: actions/setup-java@v4.2.2
        with:
          distribution: "zulu" # See 'Supported distributions' for available options
          java-version: "17"
          cache: "gradle"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          validate-wrappers: true
          gradle-version: current
          gradle-home-cache-cleanup: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set environment
        run: |
          echo '${{ secrets.GOOGLE_SERVICE_JSON }}' | base64 -d > ./app-comssa/google-services.json
          echo '${{ secrets.LOCAL_PROPERTIES }}' | base64 -d > ./local.properties
          echo '${{ secrets.FONTS }}' | base64 -d > ./core/compose-core/src/main/res/values/font_certs.xml

      - name: Build with Gradle
        run: ./gradlew app-comssa:assembleRelease

      - name: Build Release AAB
        id: buildRelease
        run: ./gradlew app-comssa:bundleRelease

      - name: Sign AAB
        id: sign
        uses: keelim/upload-google-play@0.0.2
        with:
          type: sign
          releaseDirectory: app-comssa/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.COMSSA_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Create service_account.json
        id: createServiceAccount
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Deploy to Play Store
        id: deploy
        uses: keelim/upload-google-play@0.0.2
        with:
          type: upload
          serviceAccountJson: service_account.json
          packageName: com.keelim.comssa
          releaseFiles: app-comssa/build/outputs/bundle/release/app-comssa-release.aab
          track: production
          status: completed
          changesNotSentForReview: false
