on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: cache gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: set up JDK 17
        uses: actions/setup-java@v4.0.0
        with:
          distribution: "zulu" # See 'Supported distributions' for available options
          java-version: "17"
          cache: "gradle"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.0.0
        with:
          gradle-version: current
          gradle-home-cache-cleanup: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Add Google Service Json
        run: echo '${{ secrets.MYGRADE_GOOGLE_SERVICES_JSON }}' > ./app-my-grade/google-services.json

      - name: ADD LOCAL PROPERTIES
        env:
          APOD_API_KEY: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo '${{ secrets.LOCAL_PROPERTIES }}' > ./local.properties

      - name: Build with Gradle
        run: ./gradlew app-my-grade:assembleRelease

      - name: Build Release AAB
        id: buildRelease
        run: ./gradlew app-my-grade:bundleRelease

      - name: Sign AAB
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app-my-grade/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.MYGRADE_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload AAB
        id: uploadArtifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app-my-grade/build/outputs/bundle/release/app-my-grade-release.aab

      - name: Create service_account.json
        id: createServiceAccount
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Deploy to Play Store (BETA)
        id: deploy
        uses: r0adkll/upload-google-play@v1.1.2
        with:
          serviceAccountJson: service_account.json
          packageName: com.keelim.mygrade
          releaseFiles: app-my-grade/build/outputs/bundle/release/app-my-grade-release.aab
          track: production
          status: completed
          changesNotSentForReview: false
