name: ci

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run CI when build release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: set up JDK 21
        uses: actions/setup-java@v5.0.0
        with:
          distribution: "zulu" # See 'Supported distributions' for available options
          java-version: "21"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set environment
        run: |
          echo '${{ secrets.GOOGLE_SERVICE_JSON }}' | base64 -d > ./app-cnubus/google-services.json
          echo '${{ secrets.GOOGLE_SERVICE_JSON }}' | base64 -d > ./app-comssa/google-services.json
          echo '${{ secrets.GOOGLE_SERVICE_JSON }}' | base64 -d > ./app-my-grade/google-services.json
          echo '${{ secrets.GOOGLE_SERVICE_JSON }}' | base64 -d > ./app-nanda/google-services.json
          echo '${{ secrets.GOOGLE_SERVICE_JSON }}' | base64 -d > ./app-arducon/google-services.json
          echo '${{ secrets.LOCAL_PROPERTIES }}' | base64 -d > ./local.properties
          mkdir -p ./core/component/src/commonMain/res/values/
          echo '${{ secrets.FONTS }}' | base64 -d > ./core/component/src/commonMain/res/values/font_certs.xml

      - name: Build Release AAB
        run: |
          ./gradlew app-comssa:compileDebugSources app-cnubus:compileDebugSources app-my-grade:compileDebugSources app-nanda:compileDebugSources app-arducon:compileDebugSources

