# local test with act
name: simple slack check

on:
  workflow_dispatch:

jobs:
  message:
    name: simple slack message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run script and set environment variable
        run: |
          echo "SCRIPT_RESULT=$(sh script/hello_world.sh | tail -n 1)" >> $GITHUB_ENV

      - name: post message to slack with result
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL }}
            text: "${{ env.SCRIPT_RESULT }}"
